export const products = [
  {
    id: 1,
    category: 'Tea',
    name: 'Chai',
    price: 8,
    description: 'Tea tea tea',
  },
  {
    id: 2,
    category: 'Beer',
    name: 'Chang',
    price: 6,
    description: 'Not that good',
  },
  {
    id: 3,

    category: 'Syrup',
    name: 'Aniseed Syrup',
    price: 3,
    description: 'Worth a try',
  },
  {
    id: 4,
    category: 'Cake',
    name: 'Schwarzwälder Kirschtorte',
    price: 19,
    description: 'Mmm lecker',
  },
  {
    id: 5,
    category: 'Seasoning',
    name: "Chef Anton's Cajun Seasoning",
    price: 108,
    description: "Chef Anton's Cajun Seasoning",
  },
  {
    id: 6,
    category: 'Seasoning',
    name: "Chef Anton's Gumbo Mix",
    price: 18,
    description: "Chef Anton's Gumbo Mix",
  },
  {
    id: 7,
    category: 'Other',
    name: "Grandma's Boysenberry Spread",
    price: 18,
    description: 'The best',
  },
  {
    id: 8,
    category: 'Other',
    name: "Uncle Bob's Organic Dried Pears",
    price: 35,
    description: "Uncle Bob's Organic Dried Pears",
  },
  {
    id: 9,
    category: 'Sauce',
    name: 'Northwoods Cranberry Sauce',
    price: 35,
    description: 'Straight from England',
  },
  {
    id: 10,
    category: 'Meat',
    name: 'Mishi Kobe Niku',
    price: 130,
    description: 'Mishi Kobe Niku',
  },
  {
    id: 13,
    category: 'Fish',
    name: 'Carnarvon Tigers',
    price: 56,
    description: 'Swimming tigers. Yayy.',
  },
  {
    id: 14,
    category: 'Biscuits',
    name: 'Teatime Chocolate Biscuits',
    price: 7,
    description: 'Yummy! ',
  },
  {
    id: 15,
    category: 'Seasoning',
    name: 'Alice Pepper',
    price: 75,
    description: 'Warning! Very spicy!',
  },
];
